name: accparser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-llvm:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        llvm: [17, 18, 19, 20]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/clang-${{ matrix.llvm }}
      CXX: /usr/bin/clang++-${{ matrix.llvm }}

    steps:
    - uses: actions/checkout@v4
    # NOTE: Ubuntu 24.04 ships antlr4 v4.9 but antlr4-cpp-runtime v4.10, which are API-incompatible; manually install the matching antlr4 v4.10.
    - uses: StoneMoe/setup-antlr4@v4.10.1

    - name: Add LLVM repository key
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

    - name: Add LLVM repository on Ubuntu 24.04
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      run: |
        sudo add-apt-repository -y 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.llvm }} main'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libantlr4-runtime-dev \
          build-essential \
          clang-${{ matrix.llvm }} \
          cmake

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/
        git submodule update --init
        mkdir build
        cd build
        cmake ${CMAKE_OPTIONS} -DUSE_OMPPARSER=true -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
        make

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        make test

  build-gnu:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        gnu: [9, 10, 11, 12, 13, 14]

    runs-on: ${{ matrix.os }}
    env:
      CC: /usr/bin/gcc-${{ matrix.gnu }}
      CXX: /usr/bin/g++-${{ matrix.gnu }}

    steps:
    - uses: actions/checkout@v4
    - uses: StoneMoe/setup-antlr4@v4.10.1

    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y \
          libantlr4-runtime-dev \
          build-essential \
          cmake \
          g++-${{ matrix.gnu }}

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/
        git submodule update --init
        mkdir build
        cd build
        cmake ${CMAKE_OPTIONS} -DUSE_OMPPARSER=true -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
        make

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        make test

